name: Sync Sources

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */4 * * *" 

jobs:
  Sync:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Prepare Dependences
        run: pip install requests openpyxl opencc-python-reimplemented pandas rapidfuzz zhconv

      - name: Download Scripts
        env:
          DOMAIN:       ${{ secrets.DOMAIN }}
          ACCESS_KEY:   ${{ secrets.ACCESS_KEY}}
        run: |
          mkdir -p ./sources
          python process/get.py

      - name: List results
        run: ls -lh ./code/ 2>/dev/null || echo "(no files)"
          
          
