name: Sync Sources

on:
  workflow_dispatch:
  schedule:
     - cron: "0 */4 * * *" 

jobs:
  Sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Prepare Dependences
        run: pip install requests openpyxl opencc-python-reimplemented pandas rapidfuzz zhconv

      - name: Download Scripts
        env:
          DOMAIN:       ${{ secrets.DOMAIN }}
          ACCESS_KEY:   ${{ secrets.ACCESS_KEY}}
        run: |
          mkdir -p ./sources
          python process/get.py --hide-path batch 

      - name: Run sync
        env:
          UA:          ${{ secrets.UA }}
          DOMAIN:      ${{ secrets.DOMAIN }}
          ACCESS_KEY:  ${{ secrets.ACCESS_KEY }}
          URL_PATH:    ${{ secrets.URL_PATH }}
          API_URL:     ${{ secrets.API_URL }}
          TOKEN:       ${{ secrets.TOKEN }}
        run: python ./code/iptv/code/sync/sync.py

      - name: List results
        run: ls -lh -v ./sources/ 2>/dev/null || echo "(no files)"

      - name: Extract URLs
        run: |
          scripts=(
            "Extract/extract_urls.py"
            "Channel_free/channel_free.py"
            "Channel_pay/channel_pay.py"
            "Channel_foreign/channel_foreign.py"
            "Channel_province/channel_province.py"
            "Channel_province_ground/channel_province_ground.py"
            "Channel_children/channel_children.py"
            "Channel_hk/channel_hk.py"
            "Channel_mo/channel_mo.py"
            "Channel_tw/channel_tw.py"
          )
    
          for script in "${scripts[@]}"; do
            echo "Running $script..."
            python "./code/iptv/code/process/$script"
          done

      - name: List results(extracted)
        run: ls -lh -v ./sources/temp 2>/dev/null || echo "(no files)"

      - name: Assembly files
        run: python ./code/iptv/code/assembly/assembly.py

      - name: Release files
        env:
          DOMAIN:      ${{ secrets.DOMAIN }}
          ACCESS_KEY:  ${{ secrets.ACCESS_KEY }}
        run: python ./code/iptv/code/output/output.py

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Clean up old workflow records
        run: python .github/scripts/clean.py
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WORKFLOW_NAME: "Sync Sources"
          KEEP_COUNT: 2
          
          
